apiVersion: v1
kind: Service
metadata:
  name: ${{ parameters.name }}
  labels:
    app: ${{ parameters.name }}
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
      name: http
  type: LoadBalancer
  selector:
    app: ${{ parameters.name }}
