apiVersion: v1
kind: Service
metadata:
  name: ${{ values.name }}
  labels:
    app: ${{ values.name }}
    backstage.io/kubernetes-id: ${{ values.name }}
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
      name: http
  type: LoadBalancer
  selector:
    app: ${{ values.name }}
